In [211]:
pip install inltk

In [212]:
from inltk.inltk import setup
setup('ml')

Done!


In [0]:
def tokenize_word(path,lang):
  toc = []
  with open(path) as s:
    for i in s:
      toc.append(tokenize(i, lang))
  return toc

In [214]:
from inltk.inltk import tokenize
path ='/content/drive/My Drive/Data/ml.txt'
lang = 'ml'
toc = tokenize_word(path,lang)
toc


[['▁അന്നു',
  'ണ',
  'ചര',
  '▁',
  '്',
  'ര',
  'മ',
  '്',
  'ച',
  'ത്തി',
  'വ',
  'ച',
  'ൂര',
  '്',
  '▁സ്വ',
  'ദ',
  'േ',
  '്',
  'ച',
  'ത്തി',
  'ോ',
  'ര',
  '▁കോ',
  'ച്ച്',
  'ര',
  'ര',
  '്',
  '▁കോ',
  'ലെ',
  '▁എ',
  'ത്തിലെ',
  '▁പൈതൃക',
  'വ',
  'പ',
  'ച',
  'കോ',
  'ച്ച',
  'ന്നു',
  'ണ',
  'രാ',
  'ചര',
  'ങ്',
  'ലെ',
  '▁എ',
  'മ',
  'ത്',
  '്',
  'ച',
  'ത്തി',
  '.',
  '▁ബ',
  '്',
  'ച',
  'ത്തി',
  'ജ',
  'ച',
  'കോ',
  'ച്ച',
  'മര',
  '്',
  '▁കോ',
  'ന',
  '▁ലെ',
  '▁എ',
  'റ',
  'യി',
  '്',
  'ച',
  'ത്തില',
  'കോ',
  'ച്ച',
  'വ'],
 ['▁പ്ല',
  'ര',
  '്',
  '▁കോ',
  'റ',
  '്',
  '▁കോ',
  'ച്ച്',
  'കോ',
  'ച്ച',
  'ഫ',
  'ര',
  '്',
  '▁കോ',
  'മ',
  '്',
  'ച',
  'ത്തി',
  'ത്തിലെ',
  'റു',
  'മാന',
  'ൂ',
  'ലെ',
  '▁എ',
  'ട',
  '▁',
  'ോട',
  'ക്ക്',
  'ച',
  'പ',
  'യി',
  'ര',
  '്',
  '▁കോണ',
  '▁',
  '്',
  '▁കോ',
  'ച്ച്',
  '.',
  '▁വ',
  'ത്തിലെ',
  'മ',
  '▁കോ',
  'ച്ച്',
  '▁ഒര',
  'ാ',
  'ചര',
  'ങ്',
  'ര',
  '▁കോ',
  'ച്ച',
  'ത്തി

In [215]:
mal = []
for i in toc:
  for j in i:
    mal.append(j)
len(mal)


4234

In [216]:
from inltk.inltk import setup
setup('kn') 

Done!


In [217]:
from inltk.inltk import tokenize
toc = tokenize_word('/content/drive/My Drive/Data/kn.txt','kn')
toc

[['▁ಇನ್ಸುಲಿನ್',
  '▁:',
  '▁ಇನ್ಸುಲಿನ್',
  '▁ಲ್ಯಾಟಿನ್',
  '▁ಮೂಲದ',
  '▁ಪದ',
  '.',
  '▁ಇನ್',
  'ಸು',
  'ಲಾ',
  '▁ಎಂಬ',
  '▁ಪದದಿಂದ',
  '▁ಇನ್ಸುಲಿನ್',
  '▁ಹುಟ್ಟಿಕೊಂಡಿತು',
  '.',
  '▁ಇನ್',
  'ಸು',
  'ಲಾ',
  '▁ಎಂದರೆ',
  '▁ಐಲ್ಯಾಂಡ್',
  '▁ಎಂಬ',
  '▁ಅರ್ಥ',
  '.',
  '▁ಮಾಂಸ',
  'ಲಿಯಲ್ಲಿ',
  '▁ಇರುವ',
  '▁ಕೆಲವು',
  '▁ವಿಶೇಷ',
  '▁ಜೀವ',
  'ಕಣ',
  '▁ತಂಡ',
  'ಗಳಲ್ಲಿ',
  '▁ಹುಟ್ಟಿ',
  '▁ನೇರವಾಗಿ',
  '▁ರಕ್ತ',
  'ಕ್ಕೆ',
  '▁ಸೇರುವ',
  '▁ಒಳ',
  'ಸು',
  'ರಿ',
  'ವ',
  '▁ರಸ',
  '.',
  '▁ಮೈ',
  'ಯಲ್ಲಿ',
  '▁ಸಕ್ಕರೆ',
  ',',
  '▁ಹಿಟ್ಟು',
  'ಗಳ',
  '▁ಬಳಕೆಯನ್ನು',
  '▁ಹತೋಟಿ',
  'ಗೊಳಿಸುವುದು',
  '▁ಇದರ',
  '▁ಮುಖ್ಯ',
  '▁ಕೆಲಸ',
  '.',
  '▁ಒಂದು',
  '▁ಆರೋಗ್ಯವಂತ',
  '▁ಜೀವಿ',
  'ಯಲ್ಲಿ',
  '▁ಆಹಾರದ',
  '▁ಸೇವನೆ',
  '▁ವಿಸರ್ಜನೆ',
  'ಗಳ',
  '▁ಪ್ರಮಾಣ',
  'ವೆ',
  'ಷ್ಟೇ',
  '▁ಇದ್ದರೂ',
  '▁ರಕ್ತದಲ್ಲಿ',
  '▁ಸಕ್ಕರೆಯ',
  '▁ಮಟ್ಟ',
  '▁ಮಾತ್ರ',
  '▁ಸ್ಥಿರವಾಗಿ',
  'ಯೇ',
  '▁ಇರುವುದು',
  '.',
  '▁ಈ',
  '▁ಮಟ್ಟವನ್ನು',
  '▁ಏರ',
  'ಿಸಿದಾಗ',
  '▁ಮಾಂಸ',
  'ಲಿ',
  'ಯಲ್ಲಿರುವ',
  '▁ಲ್ಯಾಂ',
  'ಗರ್',
  '▁ಹಾನ್',
  'ಸನ',
  '▁ದೀವ',
  'ುಗಳು',
  '▁ಇನ್ಸುಲಿನ್',
 

In [218]:
kannada = []
for k in toc:
  for j in k:
    kannada.append(j)
print(kannada)
print(len(kannada))

['▁ಇನ್ಸುಲಿನ್', '▁:', '▁ಇನ್ಸುಲಿನ್', '▁ಲ್ಯಾಟಿನ್', '▁ಮೂಲದ', '▁ಪದ', '.', '▁ಇನ್', 'ಸು', 'ಲಾ', '▁ಎಂಬ', '▁ಪದದಿಂದ', '▁ಇನ್ಸುಲಿನ್', '▁ಹುಟ್ಟಿಕೊಂಡಿತು', '.', '▁ಇನ್', 'ಸು', 'ಲಾ', '▁ಎಂದರೆ', '▁ಐಲ್ಯಾಂಡ್', '▁ಎಂಬ', '▁ಅರ್ಥ', '.', '▁ಮಾಂಸ', 'ಲಿಯಲ್ಲಿ', '▁ಇರುವ', '▁ಕೆಲವು', '▁ವಿಶೇಷ', '▁ಜೀವ', 'ಕಣ', '▁ತಂಡ', 'ಗಳಲ್ಲಿ', '▁ಹುಟ್ಟಿ', '▁ನೇರವಾಗಿ', '▁ರಕ್ತ', 'ಕ್ಕೆ', '▁ಸೇರುವ', '▁ಒಳ', 'ಸು', 'ರಿ', 'ವ', '▁ರಸ', '.', '▁ಮೈ', 'ಯಲ್ಲಿ', '▁ಸಕ್ಕರೆ', ',', '▁ಹಿಟ್ಟು', 'ಗಳ', '▁ಬಳಕೆಯನ್ನು', '▁ಹತೋಟಿ', 'ಗೊಳಿಸುವುದು', '▁ಇದರ', '▁ಮುಖ್ಯ', '▁ಕೆಲಸ', '.', '▁ಒಂದು', '▁ಆರೋಗ್ಯವಂತ', '▁ಜೀವಿ', 'ಯಲ್ಲಿ', '▁ಆಹಾರದ', '▁ಸೇವನೆ', '▁ವಿಸರ್ಜನೆ', 'ಗಳ', '▁ಪ್ರಮಾಣ', 'ವೆ', 'ಷ್ಟೇ', '▁ಇದ್ದರೂ', '▁ರಕ್ತದಲ್ಲಿ', '▁ಸಕ್ಕರೆಯ', '▁ಮಟ್ಟ', '▁ಮಾತ್ರ', '▁ಸ್ಥಿರವಾಗಿ', 'ಯೇ', '▁ಇರುವುದು', '.', '▁ಈ', '▁ಮಟ್ಟವನ್ನು', '▁ಏರ', 'ಿಸಿದಾಗ', '▁ಮಾಂಸ', 'ಲಿ', 'ಯಲ್ಲಿರುವ', '▁ಲ್ಯಾಂ', 'ಗರ್', '▁ಹಾನ್', 'ಸನ', '▁ದೀವ', 'ುಗಳು', '▁ಇನ್ಸುಲಿನ್', '▁ಸುರ', 'ಿಕೆಯನ್ನು', '▁ಏರಿಸ', 'ುತ್ತವೆ', '.', '▁ಇದರಿಂದ', '▁ಸಕ್ಕರೆಯ', '▁ಉತ್ಕರ್ಷಣ', 'ವಾಗಿ', '▁ಲಭಿಸ', 'ುವ', '▁ಶಕ್ತಿ', '▁ಅಂಗ', 'ಗಳ', '▁ಚಟುವಟಿಕೆಗಳಿಗೆ', '▁ದೊರೆಯುವುದು', '.', '▁ಸಿಹಿ', 'ಮೂತ್ರ

In [219]:
from inltk.inltk import setup
setup('ta') 
toc = tokenize_word('/content/drive/My Drive/Data/tamil.txt','ta')
tamil = []
for k in toc:
  for j in k:
    tamil.append(j)
print(tamil)
print(len(tamil))

Done!
['▁உறுப்பு', 'ரை', '▁1', '▁மனித', 'ப்', '▁பிற', 'ி', 'வி', 'யினர்', '▁ச', 'கல', 'ரும்', '▁சுதந்திர', 'மாகவே', '▁பிற', 'க்க', 'ின்றனர்', ';', '▁அவர்கள்', '▁மதிப்ப', 'ிலும்', ',', '▁உரிமை', 'களிலும்', '▁சமமான', 'வர்கள்', ',', '▁அவர்கள்', '▁நியாய', 'த்தையும்', '▁மன', 'ச்ச', 'ாட்சி', 'யையும்', '▁இ', 'ய', 'ற்ப', 'ண்', 'ப', 'ாகப்', '▁பெற்றவர்', 'கள்', '.', '▁அவர்கள்', '▁ஒரு', 'வரு', 'ட', 'ன', 'ொரு', 'வர்', '▁சகோதர', '▁உணர்வு', 'ப்', '▁பா', 'ங்க', 'ில்', '▁நடந்து', 'கொள்ள', 'ல்', '▁வேண்டும்', '.', '▁உறுப்பு', 'ரை', '▁2', '▁இனம்', ',', '▁நிறம்', ',', '▁பால்', ',', '▁மொழி', ',', '▁மத', 'ம்', ',', '▁அரசியல்', '▁அல்லது', '▁வேறு', '▁அபி', 'ப்பி', 'ராய', 'மு', 'டை', 'மை', ',', '▁தேசிய', '▁அல்லது', '▁சமூக', 'த்', '▁தோற்றம்', ',', '▁ஆ', 'தன', 'ம்', ',', '▁பிறப்பு', '▁அல்லது', '▁பிற', '▁அந்த', 'ஸ்', 'து', '▁என்பன', '▁போன்ற', '▁எ', 'த்த', 'கை', 'ய', '▁வேறுபாடு', 'மின்றி', ',', '▁இ', 'ப்பிர', 'கட', 'ன', 'த்தில்', '▁தர', 'ப்பட்டுள்ள', '▁எல்லா', '▁உரிமை', 'களுக்கும்', '▁சுதந்திர', 'ங்களுக்கும்', '▁எ

In [220]:
from inltk.inltk import setup
setup('ur') 
toc = tokenize_word('/content/drive/My Drive/Data/urudu.txt','ur')
urdu = []
for k in toc:
  for j in k:
    urdu.append(j)
print(urdu)
print(len(urdu))

Done!
['▁بہت', '▁سارے', '▁طریقے', '▁ہیں', '▁جو', '▁پڑھنے', '▁سے', '▁آپ', '▁کو', '▁انگریزی', '▁سیکھ', 'نے', '▁میں', '▁مدد', '▁ملتی', '▁ہے', '▁', '،', '▁لیکن', '▁خود', '▁پڑھنا', '▁زندگی', '▁کی', '▁ایک', '▁اہم', '▁مہارت', '▁ہے۔', '▁روزمر', 'ہ', '▁کی', '▁زندگی', '▁میں', '▁ہم', '▁پڑھنے', '▁کو', '▁اپنے', '▁آس', '▁پاس', '▁کی', '▁دنیا', '▁کے', '▁بارے', '▁میں', '▁معلومات', '▁حاصل', '▁کرنے', '▁کے', '▁لئے', '▁استعمال', '▁کرتے', '▁ہیں۔', '▁سڑک', '▁پر', '▁نشانات', '▁ہیں۔', '▁کیا', '▁آپ', '▁اپنی', '▁گاڑی', '▁یہاں', '▁کھڑی', '▁کرسکتے', '▁ہیں', '؟', '▁آپ', '▁کون', '▁سے', '▁دن', '▁پارک', '▁کرسکتے', '▁ہیں', '؟', '▁کتنی', '▁دیر', '▁تک', '؟', '▁اسکول', '▁یا', '▁یو', 'ٹیلی', 'ٹی', '▁کمپنیوں', '▁کے', '▁خط', '▁موجود', '▁ہیں', '▁جو', '▁میل', '▁میں', '▁آتے', '▁ہیں۔', '▁ہمارے', '▁الیکٹرانک', '▁آلات', '▁کے', '▁لئے', '▁بس', '▁کا', '▁نظام', '▁الاوقات', '▁', '،', '▁بل', '▁', '،', '▁دوائی', '▁لی', 'بل', '▁', '،', '▁اشتہارات', '▁', '،', '▁صحت', '▁کی', '▁دیکھ', '▁بھال', '▁کے', '▁پر', 'چے', '▁', '،', '▁اور', '▁تکنیکی',

In [221]:
from inltk.inltk import setup
setup('bn') 
toc = tokenize_word('/content/drive/My Drive/Data/bangali.txt','bn')
bengali = []
for k in toc:
  for j in k:
    bengali.append(j)
print(bengali)
print(len(bengali))

Done!
['▁এমন', '▁অনেকগুলি', '▁উপায়', '▁রয়েছে', '▁যা', '▁পড়া', '▁আপনাকে', '▁ইংরেজি', '▁শিখতে', '▁সহায়তা', '▁করে', '▁তবে', '▁নিজে', '▁পড়া', '▁একটি', '▁গুরুত্বপূর্ণ', '▁জীবন', '▁দক্ষতা', '।', '▁দৈনন্দিন', '▁জীবনে', '▁আমরা', '▁আমাদের', '▁চারপাশে', 'র', '▁বিশ্ব', '▁সম্পর্কে', '▁তথ্য', '▁পেতে', '▁পড়া', '▁ব্যবহার', '▁করি', '।', '▁রাস্তায়', '▁লক্ষণ', '▁রয়েছে', '।', '▁আপনি', '▁এখানে', '▁আপনার', '▁গাড়ী', '▁পার্ক', '▁করতে', '▁পারেন', '?', '▁আপনি', '▁কোন', '▁দিন', '▁পার্ক', '▁করতে', '▁পারেন', '?', '▁কত', 'ক্ষণ', '?', '▁স্কুল', '▁বা', '▁ইউটিলিটি', '▁সংস্থার', '▁চিঠি', 'গুলি', '▁মেইল', 'ে', '▁আসে', '▁in', '▁আমাদের', '▁বৈদ্য', 'ুতি', 'ন', '▁ডিভাইস', 'ের', '▁জন্য', '▁বাস', 'ের', '▁শি', 'ডি', 'উল', ',', '▁বিল', ',', '▁ওষুধের', '▁লেবেল', ',', '▁বিজ্ঞাপন', ',', '▁স্বাস্থ্যসেবা', '▁পাম', 'ফ', 'লেট', '▁এবং', '▁প্রযুক্তিগত', '▁ম্যানুয়াল', '▁রয়েছে', '।', '▁আপনি', '▁যখন', '▁কোনও', '▁দেশে', '▁নতুন', '▁হন', ',', '▁এটি', '▁আপনার', '▁প্রথম', '▁পাঠ', 'ের', '▁প্রয়োজন', '।', '▁ইউএসএ', '▁লা', 'র্ন', 'স', 

In [222]:
#data set creation
#label
# kannada = 1
# malayalam = 0
# tamil 2
#urdu 3
#bengali 4
langage = []
label = []
for i in kannada:
  langage.append(i)
  label.append(1)
for i in mal:
  langage.append(i)
  label.append(0)
for i in tamil:
  langage.append(i)
  label.append(2)
for i in urdu:
  langage.append(i)
  label.append(3)
for i in bengali:
  langage.append(i)
  label.append(4)
print(len(langage))
print(len(label))

8038
8038


In [0]:
def character_split(lang):
  final_character_set = []
  for m in lang:
    test =[]
    for a in range(0,len(m)):
      test.append(m[a]) 
    final_character_set.append(test)
  return final_character_set

In [224]:
seta = character_split(langage)
final = []
for i in seta:
  k = []
  for j in i:
      k.append(j)
  final.append(k)
len(final)

8038

In [225]:
#word2vec implimentation
num_features = 100    # Word vector dimensionality                      
min_word_count = 1   # Minimum word count                        
num_workers = 4       # Number of threads to run in parallel
context = 10          # Context window size                                                                                    
downsampling = 1e-3   # Downsample setting for frequent words

from gensim.models import word2vec
print ("Training model...")
model = word2vec.Word2Vec(final, workers=num_workers, 
                          size=num_features, min_count = min_word_count, 
                          window = context, sample = downsampling)
print ("Finish training model...")

Training model...
Finish training model...


In [0]:
#def Lstm for identfication of langa
from keras.layers import Embedding, LSTM, Dense, Dropout, Lambda, Flatten
from keras.models import Sequential, load_model, model_from_config
import keras.backend as K

def get_model():
    """Define the model."""
    model = Sequential()
    model.add(LSTM(500, dropout=0.4, recurrent_dropout=0.4, input_shape=[1,100], return_sequences=True))
    model.add(LSTM(360, recurrent_dropout=0.4,activation='relu',return_sequences=True))
    model.add(LSTM(240, recurrent_dropout=0.4,activation='relu',return_sequences=True))
    model.add(LSTM(128, recurrent_dropout=0.4))
    model.add(Dropout(0.5))
    model.add(Dense(5, activation='softmax'))


    model.compile(loss='sparse_categorical_crossentropy', optimizer='Nadam',metrics=['sparse_categorical_accuracy'])
    model.summary()

    return model

In [0]:
def makeFeatureVec(char, model, num_features):
    """Make Feature Vector from the words list of an Essay."""
    featureVec = np.zeros((num_features,),dtype="float32")
    num_words = 0.
    index2word_set = set(model.wv.index2word)
    for c in char:
        if c in index2word_set:
            num_words += 1
            featureVec = np.add(featureVec,model[c])        
    featureVec = np.divide(featureVec,num_words)
    return featureVec

def getAvgFeatureVecs(char, model, num_features):
    """Main function to generate the word vectors for word2vec model."""
    counter = 0
    FeatureVecs = np.zeros((len(char),num_features),dtype="float32")
    for c in char:
        FeatureVecs[counter] = makeFeatureVec(c, model, num_features)
        counter = counter + 1
    return FeatureVecs


In [228]:
import numpy as np
langage = getAvgFeatureVecs(final, model, num_features)
langage = np.reshape(langage, (langage.shape[0], 1, langage.shape[1]))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


In [229]:
print(langage)

[[[ 0.019409 -0.100224 -0.045614 -0.157088 ... -0.269494 -0.203821 -0.086916 -0.038818]]

 [[ 0.0166   -0.028601  0.003951 -0.054521 ... -0.120523 -0.111243 -0.048083 -0.027455]]

 [[ 0.019409 -0.100224 -0.045614 -0.157088 ... -0.269494 -0.203821 -0.086916 -0.038818]]

 [[ 0.019851 -0.094777 -0.039081 -0.154156 ... -0.274755 -0.21375  -0.094136 -0.044516]]

 ...

 [[ 0.034389 -0.050052  0.029322 -0.128273 ... -0.321728 -0.30853  -0.138505 -0.082344]]

 [[ 0.05234  -0.073945  0.044835 -0.189581 ... -0.48673  -0.474118 -0.21058  -0.124   ]]

 [[ 0.051125 -0.073454  0.038116 -0.178398 ... -0.451814 -0.440876 -0.196537 -0.115701]]

 [[ 0.002492  0.00307   0.002269  0.00163  ... -0.00367  -0.004144  0.003765  0.004675]]]


In [0]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import cohen_kappa_score
from keras.callbacks import ModelCheckpoint, EarlyStopping
import keras as k
X_train, X_test, y_train, y_test = train_test_split(langage, label, test_size=0.33, random_state=42)
y_test = k.utils.np_utils.to_categorical(y_test) 


In [231]:
y_test

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [271]:
epochs = 20
batch_size = 64
Lstm = get_model()
history = Lstm.fit(X_train, y_train, epochs=epochs,callbacks=[EarlyStopping(monitor='val_loss', patience=3)])

Model: "sequential_45"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_140 (LSTM)              (None, 1, 500)            1202000   
_________________________________________________________________
lstm_141 (LSTM)              (None, 1, 360)            1239840   
_________________________________________________________________
lstm_142 (LSTM)              (None, 1, 240)            576960    
_________________________________________________________________
lstm_143 (LSTM)              (None, 128)               188928    
_________________________________________________________________
dropout_34 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_30 (Dense)             (None, 5)                 645       
Total params: 3,208,373
Trainable params: 3,208,373
Non-trainable params: 0
___________________________________________

/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,sparse_categorical_accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


5385/5385 [==============================] - 11s 2ms/step - loss: 0.3358 - sparse_categorical_accuracy: 0.8698
Epoch 3/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2909 - sparse_categorical_accuracy: 0.8795
Epoch 4/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2657 - sparse_categorical_accuracy: 0.8825
Epoch 5/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2672 - sparse_categorical_accuracy: 0.8825
Epoch 6/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2575 - sparse_categorical_accuracy: 0.8888
Epoch 7/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2538 - sparse_categorical_accuracy: 0.8884
Epoch 8/20
5385/5385 [==============================] - 12s 2ms/step - loss: 0.2490 - sparse_categorical_accuracy: 0.8921
Epoch 9/20
5385/5385 [==============================] - 11s 2ms/step - loss: 0.2449 - sparse_categorical_accuracy: 0.8936
Epoch 10/20
5385/5385 [============

In [269]:
print('\nhistory dict:', history.history)


history dict: {'loss': [0.6574776773388561, 0.3158405480804328, 0.27545135418712374, 0.26187198642181264, 0.25804046251315593], 'sparse_categorical_accuracy': [0.78904366, 0.87613744, 0.88059425, 0.88486534, 0.8839369]}


In [273]:
import sklearn.metrics as metrics
pred = Lstm.predict(X_test)
accuracy = metrics.accuracy_score(y_test, np.round(pred))
print(accuracy)

0.8790049001130795
